engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - api/**
    - lib/**
exclude_paths:
  - "**/*.test.js"
  - migrations
