coverage:
  status:
    project:
      default:
        target: 55%    # the required coverage value
        threshold: 3%  # the leniency in hitting the target
    patch:
      default:
        target: 60%
